
server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0           # Redis服务器数据库
    host: 106.54.3.97    # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password: hello@      # Redis服务器连接密码（默认为空）
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  typeAliasesPackage: com.example.demo.model
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      lazyLoadingEnabled: true
      multipleResultSetsEnabled: true